# Generated by Django 5.0.3 on 2026-02-10 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Wert der Teilnahme / Beitrag')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='Wofür war diese Teilnahme?', max_length=255)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='pages.association')),
            ],
        ),
    ]
