# Generated by Django 5.0.3 on 2026-02-10 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='entry_date',
            field=models.DateField(null=True, verbose_name='Eintrittsdatum'),
        ),
        migrations.AddField(
            model_name='association',
            name='head_of_association',
            field=models.CharField(max_length=200, null=True, verbose_name='Leiter/in der Assocation'),
        ),
        migrations.AddField(
            model_name='association',
            name='member_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Anzahl Mitglieder'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name des Mitglieds')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pages.association', verbose_name='Association')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['name'],
            },
        ),
    ]
