# Generated by Django 5.0.3 on 2026-02-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_association_entry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_member_count', models.PositiveIntegerField(default=0, verbose_name='Mitglieder (Manuell)')),
                ('manual_participation_fee', models.FloatField(default=0.0, verbose_name='Beitrag (Manuell)')),
                ('is_active_override', models.BooleanField(default=True, verbose_name='Diese Daten nutzen?')),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_data', to='pages.association')),
            ],
        ),
    ]
