# Generated by Django 5.0.3 on 2026-02-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_manualstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualstats',
            name='association',
        ),
        migrations.AddField(
            model_name='manualstats',
            name='association_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Association Anzahl (Manuell)'),
        ),
    ]
