# Generated by Django 5.0.3 on 2026-02-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_manualstats_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='fee_amount',
            field=models.FloatField(default=0.0, verbose_name='Beitrag (€)'),
        ),
        migrations.AddField(
            model_name='association',
            name='fee_type',
            field=models.CharField(choices=[('once', 'Einmalig'), ('monthly', 'Monatlich'), ('yearly', 'Jährlich')], default='once', max_length=20, verbose_name='Beitragstyp'),
        ),
        migrations.AddField(
            model_name='association',
            name='head_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon (Head)'),
        ),
        migrations.AddField(
            model_name='association',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Mitgliedstatus'),
        ),
        migrations.AlterField(
            model_name='manualstats',
            name='association_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Association Anzahl/Partner (Manuell)'),
        ),
        migrations.AlterField(
            model_name='manualstats',
            name='manual_member_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Mitglieder/Members (Manuell)'),
        ),
        migrations.AlterField(
            model_name='manualstats',
            name='manual_participation_fee',
            field=models.FloatField(default=0.0, verbose_name='Beitrag/Participation (Manuell)'),
        ),
    ]
